services:
  db:
    image: mysql:8.0 # ou a versão do MySQL que preferir
    container_name: to_do_list_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=ToDoList1234@
      - MYSQL_DATABASE=to_do_list_db
      - MYSQL_USER=to_do_user
      - MYSQL_PASSWORD=ToDoList1234@
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
