services:
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: to_do_list_db
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=ToDoList1234@
      - MSSQL_PID=Developer
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: